language: csharp
solution: Ndi.sln
install:
  - nuget restore Ndi.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Ndi.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Ndi.UnitTests/bin/Release/Ndi.UnitTests.dll